name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: 'build mayhem fuzzing container'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: mayhem/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      image: ${{ steps.meta.outputs.tags }}

  mayhem:
    needs: build
    name: 'fuzz ${{ matrix.mayhemfile }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mayhemfile:
          - mayhem/chain-spec.mayhemfile
          - mayhem/fork-tree.mayhemfile
          - mayhem/grandpa-justification-parse.mayhemfile
          - mayhem/header-parse.mayhemfile
          - mayhem/json-rpc-call.mayhemfile
          - mayhem/multiaddr-bytes.mayhemfile
          - mayhem/multiaddr-text.mayhemfile
          - mayhem/multihash.mayhemfile
          - mayhem/network-connection-encrypted.mayhemfile
          - mayhem/network-connection-raw.mayhemfile
          - mayhem/peer-id.mayhemfile
          - mayhem/proof-node-decode.mayhemfile
          - mayhem/protocol-block-announce-decode.mayhemfile
          - mayhem/protocol-block-announces-handshake-decode.mayhemfile
          - mayhem/protocol-blocks-request-decode.mayhemfile
          - mayhem/protocol-blocks-response-decode.mayhemfile
          - mayhem/protocol-grandpa-warp-sync-response-decode.mayhemfile
          - mayhem/protocol-grandpa-notification-decode.mayhemfile
          - mayhem/protocol-identify-response-decode.mayhemfile
          - mayhem/protocol-state-response-decode.mayhemfile
          - mayhem/protocol-storage-call-proof-response-decode.mayhemfile
          - mayhem/wasm-module-wasmi.mayhemfile
          - mayhem/wasm-module-wasmtime.mayhemfile

    steps:
      - uses: actions/checkout@v2

      - name: Start analysis for ${{ matrix.mayhemfile }}
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ needs.build.outputs.image }} --file ${{ matrix.mayhemfile }} --duration 300
          sarif-output: sarif
